# Generated by Django 3.2.3 on 2021-05-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegekhajagharapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='displaypicture',
        ),
    ]
