# Generated by Django 3.2 on 2021-04-20 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collegekhajagharapp', '0007_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
